const $ = s => document.querySelector(s);
const currentUser = 'Alex Morgan';
const people = ['Alex Morgan', 'Lin Chen', 'Jordan Patel', 'Riley Silva', 'Priya Shah', 'Quality Team'];
const lifecycleDefinitions = {
  Part: { Draft: ['In Review'], 'In Review': ['Draft', 'Released'], Released: [] },
  Document: { Draft: ['In Review'], 'In Review': ['Draft', 'Released'], Released: [] },
  'Change Request': { Draft: ['Submitted'], Submitted: ['In Review', 'Rejected'], 'In Review': ['Approved', 'Rejected'], Approved: ['Implemented'], Rejected: [], Implemented: [] },
  'Change Order': { Draft: ['Submitted'], Submitted: ['In Review', 'Rejected'], 'In Review': ['Approved', 'Rejected'], Approved: ['Released'], Rejected: [], Released: [] }
};
const workflowDefinitions = [
  { id: 'engineering-change', name: 'Engineering Change', objectTypes: ['Change Request', 'Change Order'], description: 'Evaluates impacts and controls implementation of technical changes.', escalationHours: 48, steps: [{ name: 'Engineering review', role: 'Engineering', approval: true }, { name: 'Quality approval', role: 'Quality', approval: true }, { name: 'Implementation', role: 'Change owner', approval: false }] },
  { id: 'product-release', name: 'New Product Release', objectTypes: ['Part', 'Document'], description: 'Routes designs through engineering, quality, and manufacturing approval.', escalationHours: 72, steps: [{ name: 'Engineering approval', role: 'Engineering', approval: true }, { name: 'Quality approval', role: 'Quality', approval: true }, { name: 'Manufacturing approval', role: 'Manufacturing', approval: true }] }
];
const records = [
  { id: 'ECR-2026-042', title: 'Update battery enclosure venting', type: 'Change Request', state: 'In Review', assignee: 'Alex Morgan', dueDate: '2026-09-12', workflow: 'engineering-change', submitted: true },
  { id: 'ECO-2026-038', title: 'Qualify alternate motor supplier', type: 'Change Order', state: 'Approved', assignee: 'Lin Chen', dueDate: '2026-09-15', workflow: 'engineering-change', submitted: true },
  { id: 'ECR-2026-041', title: 'Correct chassis drawing tolerance', type: 'Change Request', state: 'Draft', assignee: 'Jordan Patel', dueDate: '2026-09-10', workflow: 'engineering-change', submitted: false },
  { id: 'MCO-2026-012', title: 'Revise assembly work instruction', type: 'Change Order', state: 'Submitted', assignee: 'Riley Silva', dueDate: '2026-09-18', workflow: 'engineering-change', submitted: true },
  { id: 'NX-200-001', title: 'Main chassis assembly', type: 'Part', state: 'In Review', assignee: 'Lin Chen', dueDate: '2026-09-13', workflow: 'product-release', submitted: true },
  { id: 'DOC-1018', title: 'Supplier qualification package', type: 'Document', state: 'In Review', assignee: 'Alex Morgan', dueDate: '2026-09-11', workflow: 'product-release', submitted: true }
];
let tasks = [
  { id: 'TSK-101', recordId: 'ECR-2026-042', name: 'Engineering review', assignee: 'Alex Morgan', status: 'Open', dueDate: '2026-09-12', approval: true, escalated: false },
  { id: 'TSK-102', recordId: 'ECR-2026-042', name: 'Quality approval', assignee: 'Quality Team', status: 'Pending', dueDate: '2026-09-12', approval: true, escalated: false },
  { id: 'TSK-103', recordId: 'ECO-2026-038', name: 'Implementation', assignee: 'Lin Chen', status: 'Open', dueDate: '2026-09-15', approval: false, escalated: false },
  { id: 'TSK-104', recordId: 'DOC-1018', name: 'Engineering approval', assignee: 'Alex Morgan', status: 'Open', dueDate: '2026-09-11', approval: true, escalated: true },
  { id: 'TSK-105', recordId: 'NX-200-001', name: 'Quality approval', assignee: 'Quality Team', status: 'Open', dueDate: '2026-09-13', approval: true, escalated: false }
];
const auditEvents = [];
const dateText = date => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${date}T12:00:00`));
function audit(recordId, action, comment = '') { auditEvents.unshift({ recordId, action, comment, actor: currentUser, at: new Date().toISOString() }); }
function recordFor(id) { return records.find(r => r.id === id); }
function tasksFor(id) { return tasks.filter(t => t.recordId === id); }
function statePill(state) { const tone = ['Released', 'Approved', 'Implemented', 'Completed'].includes(state) ? 'released' : state === 'Rejected' ? 'rejected' : 'inwork'; return `<span class="pill ${tone}">${state}</span>`; }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function releaseGuard(record, target) { return target === 'Released' && tasksFor(record.id).filter(t => t.approval).some(t => t.status !== 'Approved') ? 'All required workflow approvals must be approved before release.' : ''; }
function transition(record, target, comment = '') { const allowed = lifecycleDefinitions[record.type]?.[record.state] || []; if (!allowed.includes(target)) return toast(`Invalid lifecycle transition: ${record.state} → ${target}.`); const blocked = releaseGuard(record, target); if (blocked) return toast(blocked); const previousState = record.state; record.state = target; audit(record.id, `Moved ${record.type} from ${previousState} to ${target}`, comment); renderAll(); toast(`${record.id} moved to ${target}.`); }
function createTasks(record) { const definition = workflowDefinitions.find(w => w.id === record.workflow); if (!definition) return; definition.steps.forEach((step, index) => tasks.push({ id: `TSK-${Date.now()}-${index}`, recordId: record.id, name: step.name, assignee: index === 0 ? record.assignee : step.role === 'Quality' ? 'Quality Team' : 'Lin Chen', status: index === 0 ? 'Open' : 'Pending', dueDate: record.dueDate, approval: step.approval, escalated: false })); }
function submit(record, comment = '') { if (record.state !== 'Draft') return toast('Only draft records can be submitted.'); record.state = 'Submitted'; record.submitted = true; createTasks(record); audit(record.id, 'Submitted to workflow', comment); renderAll(); toast(`${record.id} submitted and tasks assigned.`); }
function performTask(task, action, comment = '') { const record = recordFor(task.recordId); if (!record || !['Open', 'Pending'].includes(task.status)) return; if (action === 'reassign') { const assignee = prompt('Reassign task to:', task.assignee); if (!assignee?.trim()) return; task.assignee = assignee.trim(); audit(record.id, `Reassigned ${task.name} to ${task.assignee}`, comment); } else if (action === 'approve') { task.status = 'Approved'; audit(record.id, `Approved ${task.name}`, comment); } else if (action === 'reject') { task.status = 'Rejected'; record.state = 'Rejected'; audit(record.id, `Rejected ${task.name}`, comment); } else { task.status = 'Completed'; audit(record.id, `Completed ${task.name}`, comment); }
  if (['Approved', 'Completed'].includes(task.status)) { const next = tasksFor(record.id).find(t => t.status === 'Pending'); if (next) next.status = 'Open'; }
  const approvals = tasksFor(record.id).filter(t => t.approval); if (approvals.length && approvals.every(t => t.status === 'Approved') && record.state === 'In Review') { record.state = 'Approved'; audit(record.id, 'Workflow approvals completed'); }
  renderAll(); toast(`${task.name} ${task.status.toLowerCase()}.`);
}
function openCommentDialog(taskId, action) { const comment = prompt(`${action[0].toUpperCase() + action.slice(1)} comment (optional):`, ''); if (comment === null) return; performTask(tasks.find(t => t.id === taskId), action, comment); }
function renderParts() { const parts = records.filter(r => ['Part', 'Document'].includes(r.type)); $('#partsTable').innerHTML = parts.map(r => `<tr><td><strong>${r.id}</strong></td><td>${escapeHtml(r.title)}</td><td>C</td><td>${statePill(r.state)}</td><td>${r.assignee}</td><td>${dateText(r.dueDate)}</td></tr>`).join(''); }
function renderChanges() { const changes = records.filter(r => r.type.includes('Change')); $('#changesTable').innerHTML = changes.map(r => { const actions = r.state === 'Draft' ? `<button class="mini-btn" data-submit="${r.id}">Submit</button>` : `${r.state === 'Approved' && lifecycleDefinitions[r.type]?.[r.state]?.includes('Released') ? `<button class="mini-btn approve" data-transition="Released" data-record="${r.id}">Release</button>` : ''}<button class="mini-btn" data-record="${r.id}">Tasks</button>`; return `<tr><td><strong>${r.id}</strong></td><td>${escapeHtml(r.title)}</td><td>${r.type}</td><td>${statePill(r.state)}</td><td>${r.assignee}</td><td>${dateText(r.dueDate)}</td><td>${actions}</td></tr>`; }).join(''); }
function renderTasks() { const visible = tasks.filter(t => t.status === 'Open' || t.status === 'Pending'); $('#taskList').innerHTML = visible.map(t => { const r = recordFor(t.recordId); const mine = t.assignee === currentUser; const taskActions = t.status === 'Open' && mine ? (t.approval ? `<button class="mini-btn approve" data-task="${t.id}" data-action="approve">Approve</button><button class="mini-btn danger" data-task="${t.id}" data-action="reject">Reject</button>` : `<button class="mini-btn approve" data-task="${t.id}" data-action="complete">Complete</button>`) : ''; return `<article class="task-row"><div><strong>${t.name}</strong><p>${r.id} · ${escapeHtml(r.title)}</p><small>Assigned to ${t.assignee} · Due ${dateText(t.dueDate)}${t.escalated ? ' · <b class="escalation">Escalated</b>' : ''}</small></div><div class="task-actions">${statePill(t.status)}${taskActions}<button class="mini-btn" data-task="${t.id}" data-action="reassign">Reassign</button></div></article>`; }).join('') || '<p class="subtle">No active workflow tasks.</p>'; }
function renderWorkflows() { $('#workflowCards').innerHTML = workflowDefinitions.map(w => `<article class="panel workflow-card"><span class="pill released">ACTIVE</span><h3>${w.name}</h3><p>${w.description}</p><p class="workflow-rule">Escalate after ${w.escalationHours} hours · ${w.steps.map(s => s.name).join(' → ')}</p><footer><span>${tasks.filter(t => recordFor(t.recordId)?.workflow === w.id && ['Open','Pending'].includes(t.status)).length} active tasks</span><span>${w.steps.filter(s => s.approval).length} approvals required</span></footer></article>`).join(''); }
function renderAudit() { $('#auditList').innerHTML = auditEvents.slice(0, 6).map(e => `<li><strong>${e.actor}</strong> ${e.action}${e.comment ? ` — “${escapeHtml(e.comment)}”` : ''}<small>${new Date(e.at).toLocaleString()}</small></li>`).join('') || '<li>Immutable audit events will appear as workflow actions occur.</li>'; }
function renderAll() { renderParts(); renderChanges(); renderTasks(); renderWorkflows(); renderAudit(); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2800); }
function showView(name) { document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === name)); document.querySelectorAll('.nav-item').forEach(v => v.classList.toggle('active', v.dataset.view === name)); $('#crumb').textContent = ({ home: 'Workspace / Overview', parts: 'Product / Parts & Documents', bom: 'Product / Bill of Materials', classification: 'Foundation / Classification', changes: 'Process / Change Management', workflows: 'Process / Workflows', admin: 'System / Administration' })[name]; }
document.querySelectorAll('.nav-item').forEach(b => b.addEventListener('click', () => showView(b.dataset.view)));
document.addEventListener('click', e => { const submitButton = e.target.closest('[data-submit]'); const taskButton = e.target.closest('[data-task]'); const recordButton = e.target.closest('[data-record]'); const transitionButton = e.target.closest('[data-transition]'); if (submitButton) submit(recordFor(submitButton.dataset.submit)); if (taskButton) openCommentDialog(taskButton.dataset.task, taskButton.dataset.action); if (transitionButton) { const comment = prompt('Release comment (optional):', ''); if (comment !== null) transition(recordFor(transitionButton.dataset.record), transitionButton.dataset.transition, comment); } else if (recordButton) { showView('workflows'); toast(`Showing tasks for ${recordButton.dataset.record}.`); } });
const modal = $('#modal'); function openModal(type = 'Part') { $('#modalType').value = type; $('#modalEyebrow').textContent = 'CREATE'; $('#modalTitle').textContent = `Create ${type}`; modal.showModal(); $('#modalName').focus(); }
$('#createBtn').addEventListener('click', () => openModal()); $('#newPartBtn').addEventListener('click', () => openModal('Part')); $('#newChangeBtn').addEventListener('click', () => openModal('Change Request')); $('#modalSubmit').addEventListener('click', () => { const title = $('#modalName').value.trim(); if (!title) return; const type = $('#modalType').value; const prefix = type === 'Change Request' ? 'ECR' : type === 'Change Order' ? 'ECO' : type === 'Document' ? 'DOC' : 'PRT'; const record = { id: `${prefix}-${Date.now().toString().slice(-5)}`, title, type, state: 'Draft', assignee: currentUser, dueDate: '2026-09-16', workflow: type === 'Part' || type === 'Document' ? 'product-release' : 'engineering-change', submitted: false }; records.unshift(record); audit(record.id, 'Created as draft'); $('#modalName').value = ''; renderAll(); toast(`${record.id} created as a draft.`); });
$('#exportBtn').addEventListener('click', () => toast('Workspace report exported successfully.'));
renderAll();
const api = async (path, options={}) => {
  const response = await fetch(`/api${path}`, { ...options, headers: { Authorization: `Basic ${btoa('admin@forgeplm.local:forgeplm-demo')}`, 'Content-Type':'application/json', ...(options.headers||{}) } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Request failed');
  return data;
};
let parts = [];
let changes = [];
function statePill(state){ return `<span class="pill ${state==='Released'||state==='Approved'?'released':'inwork'}">${state}</span>` }
function renderTables(){
  $('#partsTable').innerHTML=parts.map(p=>`<tr><td><strong>${p.number}</strong></td><td>${p.name}</td><td>${p.revision}</td><td>${statePill(p.state)}</td><td>${p.owner}</td><td>${new Date(p.updated_at).toLocaleDateString()}</td></tr>`).join('');
  $('#changesTable').innerHTML=changes.map(c=>`<tr><td><strong>${c.number}</strong></td><td>${c.title}</td><td>${c.type}</td><td>${statePill(c.state)}</td><td>${c.assignee || 'Unassigned'}</td><td>${c.due_date || '—'}</td></tr>`).join('');
let currentUser;
let parts = [];
let changes = [];
const $ = s => document.querySelector(s);
const can = permission => currentUser?.permissions.includes(permission);
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
async function api(url, options = {}) { const response = await fetch(url, { ...options, headers: { 'content-type': 'application/json', ...(options.headers || {}) } }); if (response.status === 204) return null; const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data; }
function statePill(state) { return `<span class="pill ${state === 'Released' || state === 'Approved' ? 'released' : 'inwork'}">${escapeHtml(state)}</span>`; }
function actionButton(label, action, code, permission) { return can(permission) ? `<button class="row-action" data-action="${action}" data-code="${escapeHtml(code)}">${label}</button>` : ''; }
function renderTables() {
  $('#partsTable').innerHTML = parts.map(p => `<tr><td><strong>${escapeHtml(p.number)}</strong></td><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.revision)}</td><td>${statePill(p.state)}</td><td>${escapeHtml(p.owner)}</td><td>${escapeHtml(p.modified)}</td><td>${actionButton('Revise', 'revise', p.number, 'revise')} ${p.state !== 'Released' ? actionButton('Release', 'release', p.number, 'release') : ''}</td></tr>`).join('');
  $('#changesTable').innerHTML = changes.map(c => `<tr><td><strong>${escapeHtml(c.number)}</strong></td><td>${escapeHtml(c.title)}</td><td>${escapeHtml(c.type)}</td><td>${statePill(c.state)}</td><td>${escapeHtml(c.assignee)}</td><td>${escapeHtml(c.dueDate)}</td><td>${c.state !== 'Approved' ? actionButton('Approve', 'approve', c.number, 'approve') : ''}</td></tr>`).join('');
  document.querySelectorAll('.row-action').forEach(button => button.addEventListener('click', async () => { try { await api(`/api/${button.dataset.action === 'approve' ? 'changes' : 'parts'}/${encodeURIComponent(button.dataset.code)}/${button.dataset.action}`, { method: 'POST' }); await loadRecords(); toast(`${button.dataset.code} updated.`); } catch (error) { toast(error.message, true); } }));
}
function applyPermissions() { document.querySelectorAll('[data-permission]').forEach(element => element.hidden = !can(element.dataset.permission)); document.querySelectorAll('.nav-item').forEach(item => { if (item.hidden && item.classList.contains('active')) showView('home'); }); }
function showView(name) { const view = document.getElementById(name); if (!view || document.querySelector(`[data-view="${name}"]`)?.hidden) return; document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === name)); document.querySelectorAll('.nav-item').forEach(v => v.classList.toggle('active', v.dataset.view === name)); const labels = { home:'Workspace / Overview', parts:'Product / Parts & Documents', bom:'Product / Bill of Materials', classification:'Foundation / Classification', changes:'Process / Change Management', workflows:'Process / Workflows', admin:'System / Administration' }; $('#crumb').textContent = labels[name]; }
document.querySelectorAll('.nav-item').forEach(b => b.addEventListener('click', () => showView(b.dataset.view)));
document.querySelectorAll('[data-view-target]').forEach(b => b.addEventListener('click', () => showView(b.dataset.viewTarget)));
const attention = [['↺','ECR-2026-042','Update battery enclosure venting','Due in 3 days','review','Review required'],['▤','DOC-1018','Supplier qualification package','Awaiting your approval','review','Approval needed'],['✓','ECO-2026-038','Qualify alternate motor supplier','Approved by 4 of 5 reviewers','approved','Almost complete']];
$('#attentionList').innerHTML = attention.map((a,i) => `<div class="attention-item"><div class="type-icon ${i===1?'blue':''}">${a[0]}</div><div><div class="item-title">${a[1]} · ${a[2]}</div><div class="item-meta">${a[3]}</div></div><span class="status ${a[4]}">${a[5]}</span></div>`).join('');
const activities = ['Alex Morgan promoted <strong>NX-200 Assembly</strong> to Released.','Lin Chen added revision C to <strong>Motor control board</strong>.','Priya Shah submitted <strong>ECR-2026-042</strong> for review.','Forge Assist matched 12 existing parts to your latest search.'];
$('.activity-list').innerHTML = activities.map((a,i) => `<div class="activity-row"><div class="activity-dot">${['↑','✎','↺','✦'][i]}</div><p>${a}<time>${i+1} hour${i?'s':''} ago</time></p></div>`).join('');
const bom = [['▾','NX-200-001','NX-200 Assembly','1 EA',0],['▾','ME-200-010','Main chassis','1 EA',1],['','ME-120-311','M8 hex bolt, stainless','24 EA',2],['','ME-121-107','Washer, M8','24 EA',2],['','EL-440-008','Motor control board','1 EA',1],['','EL-440-015','48V battery pack','1 EA',1]];
$('#bomTree').innerHTML = bom.map((b,i) => `<div class="tree-item ${i===0?'selected':''}" style="padding-left:${7+b[4]*25}px" data-code="${b[1]}" data-name="${b[2]}" data-qty="${b[3]}"><span>${b[0]||'·'}</span><span class="tree-code">${b[1]}</span><span class="tree-name">${b[2]}</span><span class="tree-qty">${b[3]}</span></div>`).join('');
document.querySelectorAll('.tree-item').forEach(e => e.addEventListener('click', () => { document.querySelectorAll('.tree-item').forEach(x => x.classList.remove('selected')); e.classList.add('selected'); $('#selectedPart').textContent=e.dataset.code; $('.detail-name').textContent=e.dataset.name; $('#detailQty').textContent=e.dataset.qty; }));
const flows = [['New Product Release','Routes designs through engineering, quality, and manufacturing approval.','8 active','93% on time'],['Engineering Change','Evaluates impacts and controls implementation of technical changes.','5 active','2 approvals waiting'],['Supplier Qualification','Validates new suppliers against required evidence and standards.','3 active','100% on time']];
$('#workflowCards').innerHTML = flows.map(f => `<article class="panel workflow-card"><span class="pill released">ACTIVE</span><h3>${f[0]}</h3><p>${f[1]}</p><footer><span>${f[2]}</span><span>${f[3]}</span></footer></article>`).join('');
function toast(message, error=false) { const el=$('#toast'); el.textContent=message; el.classList.toggle('error', error); el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2800); }
function runSearch() { const query=$('#globalSearch').value.trim(); if (!query) return; const hits=parts.filter(p => Object.values(p).join(' ').toLowerCase().includes(query.toLowerCase())); $('#searchResult').innerHTML = hits.length ? `<strong>Forge Assist found ${hits.length} matching item${hits.length>1?'s':''}:</strong> ${hits.map(h => `${escapeHtml(h.number)} — ${escapeHtml(h.name)}`).join(' · ')}` : `Forge Assist found no exact match for “${escapeHtml(query)}”.`; }
$('#searchBtn').addEventListener('click', runSearch); $('#globalSearch').addEventListener('keydown', e => { if(e.key==='Enter') runSearch(); }); window.addEventListener('keydown', e => { if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus();} });
const modal=$('#modal'); function openModal(type='Part') { if (!can('create')) return toast('You do not have permission to create records.', true); $('#modalType').value=type; $('#modalEyebrow').textContent='CREATE'; $('#modalTitle').textContent=`Create ${type}`; modal.showModal(); $('#modalName').focus(); }
$('#createBtn').addEventListener('click', () => openModal()); $('#newPartBtn').addEventListener('click', () => openModal('Part')); $('#newChangeBtn').addEventListener('click', () => openModal('Change Request'));
$('#modalSubmit').addEventListener('click', async event => { if(!$('#modalName').value.trim()) return; event.preventDefault(); try { const isPart = $('#modalType').value === 'Part'; const data = await api(isPart ? '/api/parts' : '/api/changes', { method:'POST', body: JSON.stringify(isPart ? { name: $('#modalName').value } : { title: $('#modalName').value }) }); if (isPart) parts.unshift(data.part); else changes.unshift(data.change); renderTables(); modal.close(); toast(`${isPart ? 'Part' : 'Change'} “${isPart ? data.part.name : data.change.title}” created as a draft.`); $('#modalName').value=''; } catch(error) { toast(error.message, true); } });
$('#exportBtn').addEventListener('click', () => toast('Workspace report exported successfully.'));
async function loadRecords() { const [partData, changeData] = await Promise.all([api('/api/parts'), api('/api/changes')]); parts = partData.parts; changes = changeData.changes; renderTables(); }
function renderProfile() { $('#profileName').textContent=currentUser.name; $('#profileRole').textContent=currentUser.role; $('#profileAvatar').textContent=currentUser.name.split(' ').map(n=>n[0]).join('').slice(0,2); $('#greetingName').textContent=currentUser.name.split(' ')[0]; }
async function startWorkspace(user) { currentUser=user; renderProfile(); applyPermissions(); await loadRecords(); $('#signInScreen').hidden=true; $('#appShell').hidden=false; }
$('#signInForm').addEventListener('submit', async event => { event.preventDefault(); $('#signInError').textContent=''; try { const data=await api('/api/auth/sign-in', { method:'POST', body:JSON.stringify({email:$('#email').value,password:$('#password').value}) }); await startWorkspace(data.user); } catch(error) { $('#signInError').textContent=error.message; } });
$('#signOutBtn').addEventListener('click', async () => { await api('/api/auth/sign-out', { method:'POST' }); currentUser=null; $('#appShell').hidden=true; $('#signInScreen').hidden=false; });
api('/api/session').then(data => startWorkspace(data.user)).catch(() => {});
function showView(name){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name)); document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name)); const labels={home:'Workspace / Overview',parts:'Product / Parts & Documents',bom:'Product / Bill of Materials',classification:'Foundation / Classification',changes:'Process / Change Management',workflows:'Process / Workflows',admin:'System / Administration'}; $('#crumb').textContent=labels[name]; }
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelectorAll('[data-view-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewTarget)));
const attention=[['↺','ECR-2026-042','Update battery enclosure venting','Due in 3 days','review','Review required'],['▤','DOC-1018','Supplier qualification package','Awaiting your approval','review','Approval needed'],['✓','ECO-2026-038','Qualify alternate motor supplier','Approved by 4 of 5 reviewers','approved','Almost complete']];
$('#attentionList').innerHTML=attention.map((a,i)=>`<div class="attention-item"><div class="type-icon ${i===1?'blue':''}">${a[0]}</div><div><div class="item-title">${a[1]} · ${a[2]}</div><div class="item-meta">${a[3]}</div></div><span class="status ${a[4]}">${a[5]}</span></div>`).join('');
const activities=['Alex Morgan promoted <strong>NX-200 Assembly</strong> to Released.','Lin Chen added revision C to <strong>Motor control board</strong>.','Priya Shah submitted <strong>ECR-2026-042</strong> for review.','Forge Assist matched 12 existing parts to your latest search.'];
$('.activity-list').innerHTML=activities.map((a,i)=>`<div class="activity-row"><div class="activity-dot">${['↑','✎','↺','✦'][i]}</div><p>${a}<time>${i+1} hour${i?'s':''} ago</time></p></div>`).join('');
function renderBom(bom){ $('#bomTree').innerHTML=bom.map((b,i)=>`<div class="tree-item ${i===0?'selected':''}" style="padding-left:${7+b.depth*25}px" data-code="${b.number}" data-name="${b.name}" data-qty="${b.quantity} ${b.unit}"><span>${b.depth===0?'▾':'·'}</span><span class="tree-code">${b.number}</span><span class="tree-name">${b.name}</span><span class="tree-qty">${b.quantity} ${b.unit}</span></div>`).join(''); document.querySelectorAll('.tree-item').forEach(e=>e.addEventListener('click',()=>{document.querySelectorAll('.tree-item').forEach(x=>x.classList.remove('selected'));e.classList.add('selected');$('#selectedPart').textContent=e.dataset.code;$('.detail-name').textContent=e.dataset.name;$('#detailQty').textContent=e.dataset.qty})); }
function renderWorkflows(flows){ $('#workflowCards').innerHTML=flows.map(f=>`<article class="panel workflow-card"><span class="pill released">${f.active?'ACTIVE':'INACTIVE'}</span><h3>${f.name}</h3><p>${f.description || ''}</p><footer><span>${f.task_count || 0} tasks</span><span>${f.pending_count || 0} pending</span></footer></article>`).join(''); }
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function runSearch(){const query=$('#globalSearch').value.trim();if(!query)return; const q=query.toLowerCase();const hits=parts.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q));$('#searchResult').innerHTML=hits.length?`<strong>Forge Assist found ${hits.length} matching item${hits.length>1?'s':''}:</strong> ${hits.map(h=>`${h.number} — ${h.name}`).join(' · ')}`:`Forge Assist found no exact match for “${query}”. Try a part number, material, document, or change ID.`}
function escapeHtml(value=''){const element=document.createElement('span');element.textContent=value;return element.innerHTML}
function renderSearchResults(payload){
  const results=payload.results||[];
  if(!results.length){$('#searchResult').innerHTML=`<p class="search-summary">No permitted records matched “${escapeHtml(payload.query)}”. Try a part number, material, document, or change ID.</p>`;return}
  $('#searchResult').innerHTML=`<p class="search-summary"><strong>Forge Assist</strong> found ${results.length} grounded, permitted result${results.length===1?'':'s'}.</p><div class="grounded-results">${results.map(result=>`<a class="grounded-result" href="${escapeHtml(result.record_url)}"><span class="result-type">${escapeHtml(result.record_type)}</span><span class="result-body"><strong>${escapeHtml(result.title)}</strong><small>${escapeHtml(result.source_snippet)}</small></span><span class="result-meta">${result.revision?`Rev. ${escapeHtml(result.revision)} · `:''}${escapeHtml(result.lifecycle_state||'')}</span></a>`).join('')}</div>`;
}
async function runSearch(){
  const query=$('#globalSearch').value.trim();if(!query)return;
  const result=$('#searchResult');result.innerHTML='<p class="search-summary">Searching permitted records…</p>';
  // Production pages inject a short-lived token after the normal sign-in flow;
  // the client never chooses access groups and does not fall back to local data.
  const token=window.FORGE_ASSIST_TOKEN;
  if(!token){result.innerHTML='<p class="search-summary search-error">Sign in is required to search Forge Assist.</p>';return}
  try{
    const response=await fetch(`/api/search?q=${encodeURIComponent(query)}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'},credentials:'same-origin'});
    const payload=await response.json();
    if(!response.ok)throw new Error(payload.error||'search_failed');
    renderSearchResults(payload);
  }catch(error){result.innerHTML='<p class="search-summary search-error">Search is temporarily unavailable. No local or unrestricted results were shown.</p>'}
}
$('#searchBtn').addEventListener('click',runSearch);$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});
const modal=$('#modal');function openModal(type='Part'){ $('#modalType').value=type;$('#modalEyebrow').textContent='CREATE';$('#modalTitle').textContent=`Create ${type}`;modal.showModal();$('#modalName').focus() }
$('#createBtn').addEventListener('click',()=>openModal());$('#newPartBtn').addEventListener('click',()=>openModal('Part'));$('#newChangeBtn').addEventListener('click',()=>openModal('Change Request'));
$('#modalSubmit').addEventListener('click',async e=>{e.preventDefault();const name=$('#modalName').value.trim(), type=$('#modalType').value;if(!name)return;try { if(type==='Part') { const number=`PRT-${Date.now().toString().slice(-6)}`; await api('/parts',{method:'POST',body:JSON.stringify({number,name})}); } else if(type==='Change Request') { const number=`ECR-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`; await api('/changes',{method:'POST',body:JSON.stringify({number,title:name})}); } else { toast('Document API is available for metadata governance and will be connected to this form next.'); return; } await loadData(); modal.close(); $('#modalName').value=''; toast(`${type} “${name}” created as a draft.`); } catch(error) { toast(error.message); }});
$('#exportBtn').addEventListener('click',()=>toast('Workspace report exported successfully.'));
async function loadData(){ try { [parts,changes] = await Promise.all([api('/parts'),api('/changes')]); const [bom,flows] = await Promise.all([api('/bom'),api('/workflows')]); renderTables(); renderBom(bom); renderWorkflows(flows); } catch(error) { $('#searchResult').textContent=`Unable to load workspace data: ${error.message}`; } }
loadData();
