PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS groups (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT);
CREATE TABLE IF NOT EXISTS user_groups (user_id INTEGER NOT NULL REFERENCES users(id), group_id INTEGER NOT NULL REFERENCES groups(id), PRIMARY KEY(user_id, group_id));
CREATE TABLE IF NOT EXISTS lifecycle_states (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, is_released INTEGER NOT NULL DEFAULT 0, sort_order INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS classifications (id INTEGER PRIMARY KEY, name TEXT NOT NULL, parent_id INTEGER REFERENCES classifications(id), attributes_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS parts (id INTEGER PRIMARY KEY, number TEXT NOT NULL UNIQUE, name TEXT NOT NULL, description TEXT, owner_id INTEGER NOT NULL REFERENCES users(id), classification_id INTEGER REFERENCES classifications(id), lifecycle_state_id INTEGER NOT NULL REFERENCES lifecycle_states(id), current_revision_id INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS part_revisions (id INTEGER PRIMARY KEY, part_id INTEGER NOT NULL REFERENCES parts(id), revision TEXT NOT NULL, lifecycle_state_id INTEGER NOT NULL REFERENCES lifecycle_states(id), description TEXT, created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(part_id, revision));
CREATE TABLE IF NOT EXISTS document_metadata (id INTEGER PRIMARY KEY, part_revision_id INTEGER REFERENCES part_revisions(id), number TEXT NOT NULL UNIQUE, title TEXT NOT NULL, file_name TEXT, mime_type TEXT, checksum TEXT, created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bom_assemblies (id INTEGER PRIMARY KEY, assembly_revision_id INTEGER NOT NULL UNIQUE REFERENCES part_revisions(id), created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bom_lines (id INTEGER PRIMARY KEY, assembly_id INTEGER NOT NULL REFERENCES bom_assemblies(id), child_revision_id INTEGER NOT NULL REFERENCES part_revisions(id), quantity REAL NOT NULL CHECK(quantity > 0), unit TEXT NOT NULL DEFAULT 'EA', find_number TEXT, UNIQUE(assembly_id, find_number));
CREATE TABLE IF NOT EXISTS change_requests (id INTEGER PRIMARY KEY, number TEXT NOT NULL UNIQUE, title TEXT NOT NULL, type TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'Draft', assignee_id INTEGER REFERENCES users(id), due_date TEXT, description TEXT, created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS change_impacts (change_id INTEGER NOT NULL REFERENCES change_requests(id), part_id INTEGER NOT NULL REFERENCES parts(id), PRIMARY KEY(change_id, part_id));
CREATE TABLE IF NOT EXISTS workflow_definitions (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, active INTEGER NOT NULL DEFAULT 1, created_by INTEGER NOT NULL REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS workflow_tasks (id INTEGER PRIMARY KEY, workflow_id INTEGER NOT NULL REFERENCES workflow_definitions(id), title TEXT NOT NULL, sequence INTEGER NOT NULL, assignee_group_id INTEGER REFERENCES groups(id), state TEXT NOT NULL DEFAULT 'Pending', UNIQUE(workflow_id, sequence));
CREATE TABLE IF NOT EXISTS approvals (id INTEGER PRIMARY KEY, change_id INTEGER REFERENCES change_requests(id), task_id INTEGER REFERENCES workflow_tasks(id), approver_id INTEGER NOT NULL REFERENCES users(id), decision TEXT NOT NULL DEFAULT 'Pending', comment TEXT, decided_at TEXT);
CREATE TABLE IF NOT EXISTS audit_events (id INTEGER PRIMARY KEY, actor_id INTEGER REFERENCES users(id), entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
